version: 2

before:
  hooks:
    - go mod tidy

archives:
  - format: none

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: akadotsh
    name: groq-go-sdk

gomod:
  proxy: true

source:
  enabled: true
  format: 'tar.gz'
  prefix_template: '{{ .ProjectName }}-{{ .Version }}/'

builds:
  - skip: true  